/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type zh_CNMessage from '../locales/zh_CN/messages.json';

export type MessageKey = keyof typeof enMessage & keyof typeof zh_CNMessage;

export type DevLocale = 'en' | 'zh_CN';
